apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: warmbly

resources:
  - namespace.yaml
  - config/configmap.yaml
  - config/external-secrets.yaml
  - config/secret-store.yaml
  - backend
  - consumer
  - worker
  - tracking
  - realtime
  - ingress
