apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: warmbly
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      serviceAccountName: warmbly-consumer
      containers:
        - name: consumer
          image: warmbly/consumer:latest
          envFrom:
            - configMapRef:
                name: warmbly-config
            - secretRef:
                name: warmbly-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
