apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: warmbly-ingress
  namespace: warmbly
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  tls:
    - hosts:
        - $(API_DOMAIN)
        - $(GATEWAY_DOMAIN)
        - $(TRACKING_DOMAIN)
      secretName: warmbly-tls
  rules:
    # API Backend
    - host: $(API_DOMAIN)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 80

    # WebSocket Gateway
    - host: $(GATEWAY_DOMAIN)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: realtime
                port:
                  number: 80

    # Tracking Pixel
    - host: $(TRACKING_DOMAIN)
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tracking
                port:
                  number: 80
