apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: warmbly-dev

resources:
  - ../../base

namePrefix: dev-

configMapGenerator:
  - name: domain-config
    literals:
      - API_DOMAIN=api.dev.warmbly.com
      - GATEWAY_DOMAIN=gateway.dev.warmbly.com
      - TRACKING_DOMAIN=t.dev.warmbly.com

# Override ConfigMap for dev
patches:
  - patch: |-
      - op: replace
        path: /data/APP_ENV
        value: dev
    target:
      kind: ConfigMap
      name: warmbly-config

images:
  - name: warmbly/backend
    newName: ghcr.io/warmbly/warmbly/backend
    newTag: dev
  - name: warmbly/consumer
    newName: ghcr.io/warmbly/warmbly/consumer
    newTag: dev
  - name: warmbly/worker
    newName: ghcr.io/warmbly/warmbly/worker
    newTag: dev
  - name: warmbly/tracking
    newName: ghcr.io/warmbly/warmbly/tracking
    newTag: dev
  - name: warmbly/realtime
    newName: ghcr.io/warmbly/warmbly/realtime
    newTag: dev
