export default interface Inbox {
    id: string;
    email: string;
    name: string;
    signature_plain: string;
    signature_html: string;
    signature_sync: boolean;
    signature_code: boolean;
    tags: string[];
    provider: string;
    status: string;
    last_synced_at: Date;
    last_id?: number | null;
    campaign_limit: number;
    min_wait_time: number;
    reply_to: string;
    tracking_domain: string;
    tracking_domain_verified: boolean;
    tracking_domain_verified_at?: Date | null;
    warmup?: Date | null;
    warmup_paused_at?: Date | null;
    warmup_base: number;
    warmup_max: number;
    warmup_increase: number;
    warmup_reply_rate: number;
    warmup_pool_type?: string;
    warmup_tag?: string;
    warmup_start_time?: string;
    warmup_end_time?: string;
    warmup_days?: number;
    created_at: Date;
    updated_at: Date;
}
