apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracking
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realtime
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 2
