#!/usr/bin/env bash
# Open the loopback-only CONFENGE operator tunnel from a workstation.
set -euo pipefail

CONFENGE_VPS_HOST="${CONFENGE_VPS_HOST:-159.195.18.88}"
CONFENGE_VPS_PORT="${CONFENGE_VPS_PORT:-2222}"
CONFENGE_VPS_USER="${CONFENGE_VPS_USER:-root}"
CONFENGE_VPS_KEY="${CONFENGE_VPS_KEY:-$HOME/.ssh/extra-consultoria-prod}"
CONFENGE_LOCAL_UI_PORT="${CONFENGE_LOCAL_UI_PORT:-5173}"
CONFENGE_LOCAL_API_PORT="${CONFENGE_LOCAL_API_PORT:-18080}"
CONFENGE_LOCAL_MAILPIT_PORT="${CONFENGE_LOCAL_MAILPIT_PORT:-18025}"
CONFENGE_LOCAL_REALTIME_PORT="${CONFENGE_LOCAL_REALTIME_PORT:-14000}"

exec ssh -N -T \
  -o BatchMode=yes \
  -o ExitOnForwardFailure=yes \
  -o ServerAliveInterval=20 \
  -o ServerAliveCountMax=3 \
  -L "${CONFENGE_LOCAL_UI_PORT}:127.0.0.1:5173" \
  -L "${CONFENGE_LOCAL_API_PORT}:127.0.0.1:8080" \
  -L "${CONFENGE_LOCAL_MAILPIT_PORT}:127.0.0.1:18025" \
  -L "${CONFENGE_LOCAL_REALTIME_PORT}:127.0.0.1:4000" \
  -p "$CONFENGE_VPS_PORT" \
  -i "$CONFENGE_VPS_KEY" \
  "${CONFENGE_VPS_USER}@${CONFENGE_VPS_HOST}"
